sensor:
  - name: StromGedacht status code
    unique_id: stromgedacht_status_code
    platform: rest
    resource_template: https://api.stromgedacht.de/v1/now?zip=76131
    headers:
      User-Agent: HomeAssistant
      Content-Type: application/json
    json_attributes:
      - state
    value_template: >
      {{ value_json['state'] }}
  - name: StromGedacht status message
    platform: template
    value_template: >-
      {% set mapper = {
          '-1' : 'Ideally use electricity now',
          '1' : 'Normal operation',
          '3' : 'Reduce consumption (save cost & CO2)',
          '4' : 'Reduce consumption (prevent power shortfalls)' } %}
      {% set state = states('sensor.stromgedacht_status_code') %}
      {{ mapper[state] if state in mapper else 'N/A' }}
